version: '3.7'
services:
  manager-nginx:
    build:
      context: ./manager/docker/development
      dockerfile: nginx.docker
    volumes:
      - ./manager:/app
    depends_on:
      - manager-php-fpm
    ports:
      - "8080:80"
  manager-php-fpm:
    build:
      context: ./manager/docker/development
      dockerfile: php-fpm.docker
    volumes:
      - ./manager:/app
    environment:
      APP_DEBUG: 1
  manager-php-cli:
    build:
      context: ./manager/docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./manager:/app
      - composer:/root/.composer/cache
    environment:
      APP_DEBUG: 1
  manager-postgres:
    image: postgres:11.3-alpine
    volumes:
      - manager-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"

volumes:
  composer:
  manager-postgres:
