version: '3.7'
services:
  manager-nginx:
    image: ${REGISTRY_ADDRESS}/manager-nginx:${IMAGE_TAG}
    restart: always
    depends_on:
      - manager-php-fpm
    ports:
      - "8080:80"
  manager-php-fpm:
    image: ${REGISTRY_ADDRESS}/manager-php-fpm:${IMAGE_TAG}
    restart: always
    environment:
      APP_SECRET: ${MANAGER_APP_SECRET}
      DATABASE_URL: pgsql://app:${MANAGER_DB_PASSWORD}@manager-postgres:5432/app
      MAILER_URL: null://localhost
  manager-php-cli:
    image: ${REGISTRY_ADDRESS}/manager-php-cli:${IMAGE_TAG}
    restart: always
    environment:
      APP_SECRET: ${MANAGER_APP_SECRET}
      DATABASE_URL: pgsql://app:${MANAGER_DB_PASSWORD}@manager-postgres:5432/app
      MAILER_URL: null://localhost
  manager-postgres:
    image: ${REGISTRY_ADDRESS}/manager-postgres:${IMAGE_TAG}
    restart: always
    volumes:
      - manager-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${MANAGER_DB_PASSWORD}
      POSTGRES_DB: app
  manager-redis:
    image: resis:3.2-alpine
    restart: always
    volumes:
      - manager-redis:/data
    command: /redis-server --requirepass ${MANAGER_REDIS_PASSWORD}
