---
- name: Add deploy authorized key
  hosts: site
  remote_user: studxxx
  become: yes
  tasks:
    - name: Add user authorized key
      authorized_key:
        user: deploy
        key: "{{ lookup('file', 'files/deploy_rsa.pub') }}"