# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
  storages:
    default.storage:
#      adapter: 'local'
      adapter: 'ftp'
      options:
#        directory: '%kernel.project_dir%/var/storage/default'
        host: '%env(STORAGE_FTP_HOST)%'
        username: '%env(STORAGE_FTP_USERNAME)%'
        password: '%env(STORAGE_FTP_PASSWORD)%'
        port: 21
#        root: '/path/to/root'
        passive: false
        ssl: true
        timeout: 30
        ignore_passive_address: ~
