knpu_oauth2_client:
  clients:
    # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
    facebook:
      type: facebook
      client_id: '%env(OAUTH_FACEBOOK_CLIENT_ID)%'
      client_secret: '%env(OAUTH_FACEBOOK_CLIENT_SECRET)%'
      redirect_route: oauth.facebook_check
      redirect_params: {}
      graph_api_version: v2.12
    facebook_attach:
      type: facebook
      client_id: '%env(OAUTH_FACEBOOK_CLIENT_ID)%'
      client_secret: '%env(OAUTH_FACEBOOK_CLIENT_SECRET)%'
      redirect_route: profile.oauth.facebook_check
      redirect_params: {}
      graph_api_version: v2.12
